### ISSUE TITLE
toJson() tries to escape single quotes producing invalid JSON

### ISSUE THREAD

**Issue by RedShift1** [tomlj/tomlj#1]
The toJson() method escapes single quotes which don't need to be escaped in JSON.

```
TomlParseResult config = Toml.parse("key = \"this is 'a test' with single quotes\"");
System.out.println(config.toJson());
```

Actual result:
```
{
  "key" : "this is \'a test\' with single quotes"
}
```

Expected result:
```
{
  "key" : "this is 'a test' with single quotes"
}
```

**Comment by Dauthjan** [comment]
@RedShift1 in #3 I've faced similar issue. If possible, you can update the source as suggested in #3 
That worked for me! 
Just for experiment, I pulled org.json's source code into tomlj's source code to validate JSONs that it is creating. It seems to work till now!
I hope @cleishm  can add a fix in his next commit!

**Comment by cleishm** [comment]
Please submit a PR with a test case (and preferably a fix too)!
