### ISSUE TITLE
TOML writer

### ISSUE THREAD

**Issue by magneticflux-** [tomlj/tomlj#16]
Besides being able to _read_ TOML files, it would be really useful to be able to write them as well. Exposing something similar to Jackson/Gson/Hjson/Jankson's type hierarchy (`JsonElement`, `JsonObject`, `JsonPrimitive`) would be great too.

**Comment by MaZderMind** [comment]
@cleishm Would you see toml serialisation within tomlj or would you rather see it as its own library? I'm currently stuck and a little unhappy https://github.com/mwanji/toml4j and might go on the detour of implementing toml serialisation. If you are interested in having this as part of tomlj we might have a chat about it.

**Comment by cleishm** [comment]
Happy to see a writer added here. Perhaps first propose the API before diving in on the whole solution?

**Comment by cleishm** [comment]
Closed by #49
