### ISSUE TITLE
Add Ability To Parse Out Of Range Longs/Doubles As BigInteger/BigDecimal

### ISSUE THREAD

**Issue by Spotlightsrule** [tomlj/tomlj#18]
I am using this project in one of my libraries to read configs, but when I try to parse a large long (eg: `9223372036854775808`), it fails with an `Integer is too large` error. While this issue is not bound to occur in the case of a properly formed TOML file, it will in the case of one that is improperly formed. To better deal with such issues of exceptionally large numbers being treated as a long/double as opposed to a BigInteger or BigDecimal and to increase the stability of the parser, an option to cast large numbers to `BigInteger` or `BigDecimal` or even a plain string would be a great feature, as in the case of json.org taking the same number and treating it a string or SnakeYAML treating it as a BigInteger. Please consider adding this as a feature or I can fork the library and attempt it myself. Thanks for making such a useful library. Much appreciated.

**Comment by cleishm** [comment]
Feel free to contribute a PR.
