### ISSUE TITLE
parsing issue

### ISSUE THREAD

**Issue by btkfrank** [tomlj/tomlj#25]
`foo = 2bar` this will be parsed as number `2`.

I looked at the toml wiki, did not find explicit indicating of this is invalid or not

[I am also asking the same question in here](https://github.com/toml-lang/toml/issues/807)

**Comment by btkfrank** [comment]
looks like this should throw an error according to [this](https://github.com/toml-lang/toml/issues/807#issuecomment-773268182)

**Comment by btkfrank** [comment]
`foo = bar` (without quote) will be treated as no key `foo` found

**Comment by cleishm** [comment]
Cannot be reproduced. Throws an error "Unexpected 'bar', expected a newline or end-of-input" and I've added a test to confirm this.
