### ISSUE TITLE
Ability to index through tables inside of a table

### ISSUE THREAD

**Issue by XavierNCline** [tomlj/tomlj#27]
For a project I'm working, it's within scope for there to be a large amount of tables nested inside of tables. It would be really good to be able to fetch a List object containing all tables found within a result, array, or table object.

**Comment by cleishm** [comment]
There are a number of methods on `TomlTable` that provide listing of keys and entries in the document. If these doesn't suffice, feel free to propose others and/or provide a PR to implement them.
