### ISSUE TITLE
ANTLR Version mismatch

### ISSUE THREAD

**Issue by MH15** [tomlj/tomlj#29]
Hello, I'm working on a project that uses ANTLR runtime v4.9.1, while Tomlj uses v4.7.2. This gives me the following error:

```
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.1
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.1
ANTLR Tool version 4.7.2 used for code generation does not match the current runtime version 4.9.1
ANTLR Runtime version 4.7.2 used for parser compilation does not match the current runtime version 4.9.1
```

Note that the Tomlk code still runs, so perhaps the solution is to turn off this error somehow.

I have two options for a quick fix:
1. I could downgrade the ANTLR version in my project to match.
2. I could fork Tomlj and compile it locally with v4.9.1.

However, I'm wondering if there's a way to make this nicer for the future: perhaps the ANTLR dependency could be separated? I'm not quite sure how you've set your project up.

**Comment by liutikas** [comment]
A fairly standard practice for libraries is to jarjar ANTLR (move it to a different package) and include it that way (example [androidx.room annotation processor](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:room/room-compiler/build.gradle;l=55)) . While this comes at the cost of larger binary size, it means you are not forcing ANTLR version onto downstream users. Ideally, this library did the same.

**Comment by cleishm** [comment]
@liutikas Seems not unreasonable. Perhaps we could even have a separate package for people who need to keep things slim. Feel free to propose a pull request to change that.
