### ISSUE TITLE
toJson() produces invalid and out of sequence result

### ISSUE THREAD

**Issue by Dauthjan** [tomlj/tomlj#3]
File used for testing: example-v0.4.0.toml [**one of your files in test resources**](https://github.com/tomlj/tomlj/blob/master/src/test/resources/org/tomlj/example-v0.4.0.toml)

Code:

	public static void main(String[] args) {

		TomlParseResult result = null;
		try {
			Path source = Paths.get("D:/test/example-v0.4.0.toml");
			result = Toml.parse(source);
			String value = result.toJson();
			System.out.println(value);
		} catch (Exception e) {
			System.err.println(e.getMessage());
		}
	}
**Request:** I noticed the JSON generated is not in sequence with the file, rather it's generating in alphabetical order. Can we get that in the sequence we created the toml?
**UPDATE:** I made some minor changes in the JsonSerializer.java and MutableTomlTable.java to achieve the sequence. Changes I did:

**JsonSerializer:** Removed **`.stream().sorted()`** from **`Iterator<String> iterator`**.
**MutableTomlTable:** Changed **`properties = new LinkedHashMap<>();`**

**Issue 1:** singe quote "'" having escape character "\'" which breaks the JSON validation. (line no. 111). I'm using [online JSON validator](https://jsonlint.com/)
Just had a quick look at your JsonSerializer.java. May be this is causing the issue? **_I tried removing this part and it worked as expected._**
```
if (ch == '\'') {
    out.append("\\'");
    continue;
}
```
**Issue 2:** double quote " not having escape character "\". JSON validation failed. Same line number. Maybe you missed something like this? (Just a guess). **_I added the below code, it worked as expected._**
```
if (ch == '\"') {
    out.append('\\');
    out.append('\"');
    continue;
}
```
**Issue 3:** Line no. 116 `"regex2": "I [dw]on't need \d{2} apples"` seems to be wrong. Maybe it would be `"regex2": "I [dw]on't need \\d{2} apples"` ? Same issue with single "\" noticed in Line 119, 120, 221. Line 121 is `"winpath2" : "\\ServerX\admin$\system32\"`, maybe it would be `"winpath2" : "\\\\ServerX\\admin$\\system32\\"` **_I added the below code, it worked as expected._**
```
if (ch == '\\') {
    out.append('\\');
    out.append('\\');
    continue;
}
```
Thanks in advance for this! I'm not a java coder, pardon me for mistakes!
I found toml recently and decided to explore. 

Will the  version v1.0.0-rc.1 be implemented?

**Comment by cleishm** [comment]
Please send a PR with a test case!

**Comment by cleishm** [comment]
I believe all of this has been addressed, except the order of serialization. I'm not sure that's a big concern, given the output is a json map, and json maps aren't meant to represent ordering - so parsing it will still give the right object graph.

But for consistency, I can see how having the same key order as the TOML document is nice. The easiest way is probably using a `LinkedHashMap` in the `MutableTomlTable`, rather than a regular hash map.

Do you have a test case?

**Comment by Dauthjan** [comment]
I agree, json objects are not intended for maintaining sequence. However, if a method that generates TOML from JSON is developed in future, I guess it would be easier to compare. For the changes, I did the same change + removed `.stream().sorted()` from JsonSerializer and it worked. But no test case as of now. I'll try to push a test case asap.

**Comment by cleishm** [comment]
If it worked, it was likely a happy coincidence. Internally to the `MutableTomlTable`, the properties are stored in a hash map, which does not preserve ordering.

**Comment by Dauthjan** [comment]
Hi @cleishm 
I've added a [TestCase](https://github.com/Dauthjan/tomlj/blob/master/src/test/java/org/tomlj/JsonSerializer.java) for you. Can you please have a look?
