### ISSUE TITLE
Version 1.0.0 doesn't support parsing of arrays that contain multiple data types

### ISSUE THREAD

**Issue by guilhermesgb** [tomlj/tomlj#33]
As per https://toml.io/en/v1.0.0-rc.1#array, this is valid TOML 1.0.0-rc.1:

```
[example]
contributors = [
  "Foo Bar <foo@example.com>",
  { name = "Baz Qux", email = "bazqux@example.com", url = "https://example.com/bazqux" }
]
```

But when parsing using "org.tomlj:tomlj:1.0.0", this array is not parsed:

```
TomlParseResult result = ...

println(result.get("example"))
```

What gets printed is a `MutableTomlTable` instance of size 0.

Another query:

```
println(result.get("example.contributors"))
```
This one just prints `null`.

**Comment by cleishm** [comment]
Note that Tomlj versions and TOML versions are not the same thing. TOML 1.0.0 features, including this, are fully supported in the main branch of the repository. The main branch just needs to be released, probably as Tomlj version 1.1.0.
