### ISSUE TITLE
toJson() produces invalid JSON if a value is a JSON string

### ISSUE THREAD

**Issue by sjrd218** [tomlj/tomlj#38]
Given the toml document:
```jsonval = '{"msg":"This is invalid json"}'```

An invalid JSON document will be produced by a toJson() call.
Generated JSON from example toml:
```
{
  "jsonval" : "{"msg":"This is invalid json"}"
}
```

**Comment by cleishm** [comment]
This would be a good one for someone to submit a test for, and a fix also. Should be fairly straightfoward.

**Comment by cleishm** [comment]
This cannot be reproduced, and I've added a test case to confirm so. The output from this is correctly escaped:

```
{
  "jsonval" : "{\"msg\":\"This is invalid json\"}"
}
```
