### ISSUE TITLE
Throw an error when duplicate keys are encountered

### ISSUE THREAD

**Issue by octylFractal** [tomlj/tomlj#39]
According to the TOML spec, duplicate keys are not allowed, but this library silently ignores when there are duplicate keys, rather than producing an error. I think it would be more correct to throw an error.

Context: Gradle uses TOML for its version catalog files, but cannot produce an error when there are duplicate keys because this library does not allow detecting that.

**Comment by cleishm** [comment]
Sounds great - pull request is welcome.

**Comment by cleishm** [comment]
So I've verified that the library does correctly detect duplicate keys (#47), so I'm closing this as unreproducible.

**Comment by cleishm** [comment]
Based on your PR #40, I suspect you may be looking for an exception to be thrown in this case. However, that's not how the library works - it reports errors in via the parse result. You should inspect the `TomlParseResult#hasErrors()` and/or `TomlParseResult#errors()` methods after parsing.
