### ISSUE TITLE
tomlj incorrectly marked as a pom artifact

### ISSUE THREAD

**Issue by Temennigru** [tomlj/tomlj#43]
In the pom xml for the tomlj maven artifact, it is marked as a pom package, which is incorrect since tomj is not an aggregator artifact and has a jar. This is causing our maven resolving tool to skip the jar when resolving this artifact.

https://repo1.maven.org/maven2/org/tomlj/tomlj/1.0.0/tomlj-1.0.0.pom

```
<packaging>pom</packaging>
```

**Comment by cleishm** [comment]
@Temennigru Do you have a patch for this?

**Comment by cleishm** [comment]
@kPYKx7Ddw4n1aIKZ Any ideas on this? I've removed all the maven/POM stuff from my brain in the last years.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
@cleishm Yes, I did some research and by default the packaging type is already `jar`.

However, for some reason this was changed to `pom` after setting the `ENABLE_SIGNING` environment variable to `true`.

After setting packaging to `jar` in the build.gradle, the packaging type in the generated pom-file was correct again.

**Comment by Temennigru** [comment]
Thanks for fixing this :D
When can we expect this to be pushed to maven central?

**Comment by cleishm** [comment]
@Temennigru It's on maven central now, as version 1.1.0.
