### ISSUE TITLE
tomlj-all missing on maven central

### ISSUE THREAD

**Issue by thargor** [tomlj/tomlj#56]
With 1.1.0 tomlj switched its dependencies from "compile" to "runtime". Some build systems, like ours, only bundle compile scope dependencies by default. We need to explicitly add tomlj dependencies to our build now. This means we need to take care of dependency management for tomlj now manually. Using tomlj-all instead would be an option, but it it is not deployed to maven as of now.

Would it be possible to deploy tomlj-all to maven central as well?

Thanks for providing this great library!

**Comment by cleishm** [comment]
Verifies that the `-all` jar is available on Maven Central (in both version 1.1.0 and the recently published 1.1.1).
