### ISSUE TITLE
Malformed output when serializing TOML tables

### ISSUE THREAD

**Issue by phi-gamma** [tomlj/tomlj#57]
When serializing nested table data, e. g. the ``TomlParseResult``
obtained from deserializing this TOML file:

    [buggy]
    a = { foo = "bar", baz = ["xyzzy"] }
    b = { foo = "bar", baz = ["xyzzy"] }
    c = "quux"
    d = "quux"
    e = { foo = "bar", baz = ["xyzzy"] }
    f = "quux"

tomlj incorrectly emits simple and nested values alongside each other:

    [buggy]
      [buggy.a]
        foo="bar"
        baz=[
          "xyzzy"
        ]
      [buggy.b]
        foo="bar"
        baz=[
          "xyzzy"
        ]
      c="quux"
      d="quux"
      [buggy.e]
        foo="bar"
        baz=[
          "xyzzy"
        ]
      f="quux"

Obviously in this output the key ``f`` will be parsed as part of
``[buggy.e]``, and keys ``c`` and ``d`` to ``buggy.b`` instead of
``buggy`` where they belong in the original file.

What the serializer should do is output the nested ones as individual
sections like so:

    [buggy]
      c="quux"
      d="quux"
      f="quux"

    [buggy.a]
      foo="bar"
      baz=[
        "xyzzy"
      ]
    [buggy.b]
      foo="bar"
      baz=[
        "xyzzy"
      ]
    [buggy.e]
      foo="bar"
      baz=[
        "xyzzy"
      ]

Cherry-pick [this commit](https://github.com/phi-gamma/tomlj/commit/1dd940fe40848f650dc19df74a160dc180713b08) for a test case based on a real world Rust crate.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
I tried to solve your issue by sorting tables so that primitive values appear before nested tables and table arrays.

Since @cleishm is the only one that has write access to the repository but doesn't seem to be very active here, I can't say when/if it will be merged.

**Comment by cleishm** [comment]
@kPYKx7Ddw4n1aIKZ I assumed you had write access. I've fixed that.

**Comment by cleishm** [comment]
Fixed by #61

**Comment by phi-gamma** [comment]
Thanks a ton, I’ll give this a try soon-ish and report back!

**Comment by phi-gamma** [comment]
Confirmed fixed, thanks again @cleishm and @kPYKx7Ddw4n1aIKZ!
