### ISSUE TITLE
Toml Serializer?

### ISSUE THREAD

**Issue by qyl27** [tomlj/tomlj#58]
I want to replace my toml impl with tomlj, but how can I create an instance of TomlTable? MutableTomlTable is package private.

**Comment by kPYKx7Ddw4n1aIKZ** [comment]
As mentioned in #49, there is no API yet for creating or modifying TOML documents.
So the TOML serializer feature might not be very useful yet.

**Comment by cleishm** [comment]
Replaced by #59.
