### ISSUE TITLE
How to WRITE something to a specific toml file?

### ISSUE THREAD

**Issue by ForestRealms** [tomlj/tomlj#62]
Hello, I am looking for how to write a section (all data types of toml file) in to a specific `.toml` file, but I didn't find it. Are there any `functions` in this package that provide it?

**Comment by cleishm** [comment]
Duplicate of #58. This library currently only deals with parsing TOML documents. There is a limited API support for re-serializing the parsed document back to a file (added in #49), but there is currently no API for modifying a document or creating one from scratch.
