### ISSUE TITLE
Parser failure when parsing inline tables with empty arrays

### ISSUE THREAD

**Issue by vigneshvg** [tomlj/tomlj#66]
The parser fails to parse the following (valid) toml:

```toml
key = { value1 = 1, value2 = [] }
```

If i express this as a standard table instead of using an inline table, it works:
```toml
[key]
value1 = 1
value2 = []
```

Sample code snippet that fails:
```java
import org.tomlj.Toml;
import org.tomlj.TomlParseResult;

public class TomlTest {
  public static void main(String[] args) throws Exception {
    String s = "key = { value1 = 1, value2 = [] }";
    TomlParseResult result = Toml.parse(s);
    if (result.hasErrors()) {
      System.out.println(result.errors().toString());
    } else {
      System.out.println("no errors");
    }
  }
}
```

The output is:
```
[Unexpected '}', expected } or a comma (line 1, column 33)]
```

I tried several combinations, but any time i included an empty array in an inline table, the parser fails with a similar error message.

**Comment by cleishm** [comment]
I can't verify this issue. I've added a test to the test suite that confirms this parses correctly.
